services:
  - type: web
    name: botfarm
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn web_app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7 